import type {
  Campaign,
  Account,
  Pixel,
  Suggestion,
  ActivityLog,
  TokenStatus,
} from "./types";

export const mockAccounts: Account[] = [
  { id: "1", name: "Main Account", currency: "USD", status: "connected" },
  { id: "2", name: "Secondary Account", currency: "EUR", status: "connected" },
  { id: "3", name: "EMEA Account", currency: "EUR", status: "connected" },
  { id: "4", name: "APAC Account", currency: "VND", status: "connected" },
  { id: "5", name: "Test Sandbox", currency: "USD", status: "disconnected" },
];

export const mockPixels: Pixel[] = [
  { id: "px1", name: "Main Pixel", accountId: "1", status: "active" },
  { id: "px2", name: "Test Pixel", accountId: "1", status: "active" },
  { id: "px3", name: "Backup Pixel", accountId: "2", status: "inactive" },
  { id: "px4", name: "EMEA Pixel", accountId: "3", status: "active" },
  { id: "px5", name: "APAC Pixel", accountId: "4", status: "active" },
  { id: "px6", name: "Sandbox Pixel", accountId: "5", status: "inactive" },
];

export const creativeOptions = [
  { id: "cr1", name: "Video - Product Demo", type: "video" },
  { id: "cr2", name: "Image - Summer Sale Banner", type: "image" },
  { id: "cr3", name: "Carousel - Multi-product", type: "carousel" },
  { id: "cr4", name: "Slideshow - Brand Story", type: "slideshow" },
  { id: "cr5", name: "UGC - Customer Testimonial", type: "video" },
  { id: "cr6", name: "Static - Promo Badge", type: "image" },
];

export const mockCampaigns: Campaign[] = [
  {
    id: "camp1",
    name: "Summer Sale Campaign",
    objective: "conversion",
    status: "active",
    budget: 5000,
    dailyBudget: 200,
    spent: 3245,
    impressions: 125000,
    conversions: 342,
    createdAt: new Date("2025-10-15T10:30:00Z"),
    accountId: "1",
    pixelId: "px1",
    automations: ["auto1", "auto3"],
    targeting: { ageMin: 18, ageMax: 45, locations: ["US", "VN"] },
    creative: { id: "cr1", name: "Video - Product Demo" },
    saved: true,
  },
  {
    id: "camp2",
    name: "Brand Awareness Q4",
    objective: "reach",
    status: "active",
    budget: 8000,
    dailyBudget: 300,
    spent: 7200,
    impressions: 450000,
    conversions: 156,
    createdAt: new Date("2025-09-20T14:22:00Z"),
    accountId: "1",
    pixelId: "px1",
    automations: ["auto2"],
    targeting: { ageMin: 25, ageMax: 54, locations: ["EU", "UK"] },
    creative: { id: "cr2", name: "Image - Summer Sale Banner" },
  },
  {
    id: "camp3",
    name: "Engagement Test",
    objective: "engagement",
    status: "paused",
    budget: 2000,
    dailyBudget: 50,
    spent: 1500,
    impressions: 45000,
    conversions: 89,
    createdAt: new Date("2025-08-10T09:15:00Z"),
    accountId: "2",
    pixelId: "px3",
    automations: [],
    targeting: { ageMin: 18, ageMax: 30, locations: ["DE", "FR"] },
    creative: { id: "cr5", name: "UGC - Customer Testimonial" },
  },
  {
    id: "camp4",
    name: "Traffic Drive",
    objective: "traffic",
    status: "ended",
    budget: 3500,
    dailyBudget: 100,
    spent: 3500,
    impressions: 98000,
    conversions: 234,
    createdAt: new Date("2025-07-05T11:45:00Z"),
    accountId: "1",
    pixelId: "px2",
    automations: ["auto1"],
    targeting: { ageMin: 20, ageMax: 40, locations: ["US"] },
    creative: { id: "cr3", name: "Carousel - Multi-product" },
  },
  {
    id: "camp5",
    name: "Holiday Promo APAC",
    objective: "conversion",
    status: "active",
    budget: 12000,
    dailyBudget: 400,
    spent: 4500,
    impressions: 300000,
    createdAt: new Date("2025-07-05T11:45:00Z"),
    conversions: 890,
    accountId: "4",
    pixelId: "px5",
    automations: ["auto4"],
    targeting: { ageMin: 22, ageMax: 45, locations: ["VN", "SG"] },
    creative: { id: "cr2", name: "Image - Summer Sale Banner" },
    saved: true,
  },
  {
    id: "camp6",
    name: "Sandbox Experiment",
    objective: "conversion",
    status: "paused",
    budget: 500,
    dailyBudget: 20,
    spent: 120,
    impressions: 8000,
    conversions: 5,
    createdAt: new Date("2025-10-25T12:00:00Z"),
    accountId: "5",
    pixelId: "px6",
    automations: [],
    targeting: { ageMin: 18, ageMax: 65, locations: ["US"] },
    creative: { id: "cr6", name: "Static - Promo Badge" },
  },
  {
    id: "camp7",
    name: "EMEA Q3 Push",
    objective: "traffic",
    status: "active",
    budget: 6000,
    dailyBudget: 200,
    spent: 2000,
    impressions: 210000,
    conversions: 420,
    createdAt: new Date("2025-08-01T09:00:00Z"),
    accountId: "3",
    pixelId: "px4",
    automations: ["auto5"],
    targeting: { ageMin: 30, ageMax: 60, locations: ["DE", "FR", "UK"] },
    creative: { id: "cr4", name: "Slideshow - Brand Story" },
    saved: false,
  },
  {
    id: "camp8",
    name: "New Product Launch",
    objective: "conversion",
    status: "active",
    budget: 15000,
    dailyBudget: 500,
    spent: 3000,
    impressions: 500000,
    conversions: 1200,
    createdAt: new Date("2025-10-05T07:30:00Z"),
    accountId: "1",
    pixelId: "px2",
    automations: ["auto1", "auto6"],
    targeting: { ageMin: 18, ageMax: 35, locations: ["US", "CA"] },
    creative: { id: "cr1", name: "Video - Product Demo" },
    saved: true,
  },
  {
    id: "camp9",
    name: "Retargeting - Cart Abandoners",
    objective: "conversion",
    status: "active",
    budget: 2500,
    dailyBudget: 80,
    spent: 900,
    impressions: 65000,
    conversions: 320,
    createdAt: new Date("2025-09-18T10:00:00Z"),
    accountId: "1",
    pixelId: "px1",
    automations: ["auto3"],
    targeting: { ageMin: 25, ageMax: 55, locations: ["US"] },
    creative: { id: "cr5", name: "UGC - Customer Testimonial" },
  },
  {
    id: "camp10",
    name: "Low Budget Test",
    objective: "engagement",
    status: "paused",
    budget: 300,
    dailyBudget: 10,
    spent: 300,
    impressions: 7000,
    conversions: 12,
    createdAt: new Date("2025-11-02T09:00:00Z"),
    accountId: "2",
    pixelId: "px3",
    automations: [],
    targeting: { ageMin: 18, ageMax: 28, locations: ["FR"] },
    creative: { id: "cr6", name: "Static - Promo Badge" },
  },
  {
    id: "camp11",
    name: "Whitelist Influencers",
    objective: "reach",
    status: "active",
    budget: 4200,
    dailyBudget: 140,
    spent: 2100,
    impressions: 120000,
    conversions: 78,
    createdAt: new Date("2025-09-10T13:45:00Z"),
    accountId: "3",
    pixelId: "px4",
    automations: ["auto7"],
    targeting: { ageMin: 20, ageMax: 40, locations: ["UK"] },
    creative: { id: "cr3", name: "Carousel - Multi-product" },
  },
  {
    id: "camp12",
    name: "Seasonal Clearance",
    objective: "conversion",
    status: "ended",
    budget: 4000,
    dailyBudget: 133,
    spent: 4000,
    impressions: 140000,
    conversions: 560,
    createdAt: new Date("2025-06-12T10:20:00Z"),
    accountId: "4",
    pixelId: "px5",
    automations: ["auto4"],
    targeting: { ageMin: 28, ageMax: 55, locations: ["VN"] },
    creative: { id: "cr2", name: "Image - Summer Sale Banner" },
  },
];

export const mockSuggestions: Suggestion[] = [
  {
    id: "sug1",
    type: "creative",
    title: "Biến thể creative hiệu quả cao",
    reason: "CTR cao hơn 15% so với mức trung bình",
    impressions: 125000,
    createdAt: new Date(),
    campaignId: "camp1",
    priority: "high",
    status: "new",
  },
  {
    id: "sug2",
    type: "targeting",
    title: "Mở rộng nhóm tuổi 25-34",
    reason: "ROAS 2.3x trong phân khúc này",
    impressions: 98000,
    createdAt: new Date(),
    campaignId: "camp1",
    priority: "medium",
    status: "new",
  },
  {
    id: "sug3",
    type: "budget",
    title: "Tăng ngân sách hàng ngày",
    reason: "Giai đoạn học chưa hoàn tất",
    impressions: 45000,
    createdAt: new Date(),
    campaignId: "camp2",
    priority: "low",
    status: "accepted",
  },
  {
    id: "sug4",
    type: "creative",
    title: "Thử video creative",
    reason: "Tương tác video cao gấp 3.5 lần",
    impressions: 156000,
    createdAt: new Date(),
    campaignId: "camp2",
    priority: "high",
    status: "new",
  },
  {
    id: "sug5",
    type: "audience",
    title: "Nhắm lại người dùng desktop",
    reason: "Giá trị giỏ hàng cao từ desktop",
    impressions: 65000,
    createdAt: new Date(),
    campaignId: "camp9",
    priority: "medium",
    status: "new",
  },
  {
    id: "sug6",
    type: "creative",
    title: "Thử carousel cho sản phẩm mới",
    reason: "CTR danh mục cao hơn",
    impressions: 50000,
    createdAt: new Date(),
    campaignId: "camp8",
    priority: "high",
    status: "new",
  },
  {
    id: "sug7",
    type: "budget",
    title: "Giảm ngân sách hàng ngày",
    reason: "Tỷ lệ chuyển đổi thấp trong 7 ngày gần đây",
    impressions: 7000,
    createdAt: new Date(),
    campaignId: "camp10",
    priority: "low",
    status: "ignored",
  },
];

export const mockActivityLogs: ActivityLog[] = [
  {
    id: "log1",
    action: "Campaign created",
    campaignName: "Summer Sale Campaign",
    campaignId: "camp1",
    timestamp: "2025-11-04T16:45:00Z",
    status: "success",
  },
  {
    id: "log2",
    action: "Budget updated",
    campaignName: "Brand Awareness Q4",
    campaignId: "camp2",
    timestamp: "2025-11-04T14:20:00Z",
    status: "success",
  },
  {
    id: "log3",
    action: "Automation paused",
    campaignName: "Summer Sale Campaign",
    campaignId: "camp1",
    timestamp: "2025-11-04T12:10:00Z",
    status: "success",
  },
  {
    id: "log4",
    action: "Sync failed",
    campaignName: "All campaigns",
    timestamp: "2025-11-04T10:00:00Z",
    status: "error",
    details: "API rate limit exceeded",
  },
  {
    id: "log5",
    action: "Campaign paused",
    campaignName: "Engagement Test",
    campaignId: "camp3",
    timestamp: "2025-11-03T09:30:00Z",
    status: "success",
  },
  {
    id: "log6",
    action: "Creative changed",
    campaignName: "New Product Launch",
    campaignId: "camp8",
    timestamp: "2025-10-15T08:00:00Z",
    status: "success",
  },
  {
    id: "log7",
    action: "Campaign ended",
    campaignName: "Traffic Drive",
    campaignId: "camp4",
    timestamp: "2025-09-30T18:00:00Z",
    status: "success",
  },
  {
    id: "log8",
    action: "Suggestion applied",
    campaignName: "Brand Awareness Q4",
    campaignId: "camp2",
    timestamp: "2025-10-30T13:00:00Z",
    status: "success",
    details: "Applied creative test",
  },
];

export const mockTokenStatus: TokenStatus[] = [
  {
    accountId: "1",
    token: "token_main_abc123",
    expiresAt: "2025-11-15T23:59:59Z",
    status: "valid",
    lastSync: "2025-11-04T17:00:00Z",
  },
  {
    accountId: "2",
    token: "token_secondary_def456",
    expiresAt: "2025-10-30T23:59:59Z",
    status: "expired",
    lastSync: "2025-10-29T08:00:00Z",
  },
  {
    accountId: "4",
    token: "token_apac_xyz789",
    expiresAt: "2025-12-01T23:59:59Z",
    status: "valid",
    lastSync: "2025-11-03T10:00:00Z",
  },
];

export const mockUsers = [
  { id: "u1", name: "Alice", role: "admin", accountId: "1" },
  { id: "u2", name: "Bao", role: "analyst", accountId: "4" },
  { id: "u3", name: "Carla", role: "manager", accountId: "3" },
];
